 #IO 管脚约束
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
# UART 快速控制侧信道 (fast-control link; ~82ms 程序上传 / ~sub-ms scan step vs ~1s JTAG-Tcl).
# 正点原子达芬奇 ATK-DF7A35 板载 USB-UART (CH340C, U14, 3.3V 直连无电平转换) -> "USB_UART" 连接器.
# 引脚来自达芬奇 IO 引脚分配表 + 原理图 POWER&UART.SchDoc: uart_rxd=U5(FPGA收<-CH340_TXD), uart_txd=T6(FPGA发->CH340_RXD).
# 方向与 zlc_uart_bridge 一致 (uart_rx=input, uart_tx=output). 换板只改这两行.
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports uart_rx]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS33} [get_ports uart_tx]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports cooling]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports cooling_pgc]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports repump]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports probe]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports pushout]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports state_pre]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports trig]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports coil]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports grey_cooling]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports trap]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports UV]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports emCCD]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports microwave]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports address]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports GND1]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports GND4]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports GND5]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports GND6]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports GND7]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports GND8]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports GND9]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports GND10]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports GND11]

set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports cooling_shutter]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports GND12]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports repump_shutter]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports GND13]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports probe_shutter]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports GND14]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports bias]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports GND15]

#da模块的constrains
set_property PACKAGE_PIN V9 [get_ports {da_dipole[0]}]
set_property PACKAGE_PIN W9 [get_ports {da_dipole[1]}]
set_property PACKAGE_PIN Y9 [get_ports {da_dipole[2]}]
set_property PACKAGE_PIN V8 [get_ports {da_dipole[3]}]
set_property PACKAGE_PIN U7 [get_ports {da_dipole[4]}]
set_property PACKAGE_PIN AB7 [get_ports {da_dipole[5]}]
set_property PACKAGE_PIN V7 [get_ports {da_dipole[6]}]
set_property PACKAGE_PIN AB6 [get_ports {da_dipole[7]}]
set_property PACKAGE_PIN AB8 [get_ports {da_dipole[8]}]
set_property PACKAGE_PIN AA8 [get_ports {da_dipole[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_dipole[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk0]
set_property PACKAGE_PIN Y8 [get_ports da_clk0]

set_property PACKAGE_PIN P15 [get_ports {da_bias_y[9]}]
set_property PACKAGE_PIN R16 [get_ports {da_bias_y[8]}]
set_property PACKAGE_PIN P17 [get_ports {da_bias_y[7]}]
set_property PACKAGE_PIN N17 [get_ports {da_bias_y[6]}]
set_property PACKAGE_PIN R18 [get_ports {da_bias_y[5]}]
set_property PACKAGE_PIN V20 [get_ports {da_bias_y[4]}]
set_property PACKAGE_PIN T18 [get_ports {da_bias_y[3]}]
set_property PACKAGE_PIN V19 [get_ports {da_bias_y[2]}]
set_property PACKAGE_PIN U17 [get_ports {da_bias_y[1]}]
set_property PACKAGE_PIN U18 [get_ports {da_bias_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk1]
set_property PACKAGE_PIN R14 [get_ports da_clk1]

#da_模块2用
set_property PACKAGE_PIN N22 [get_ports {da_bias_x[0]}]
set_property PACKAGE_PIN M22 [get_ports {da_bias_x[1]}]
set_property PACKAGE_PIN M21 [get_ports {da_bias_x[2]}]
set_property PACKAGE_PIN L21 [get_ports {da_bias_x[3]}]
set_property PACKAGE_PIN K22 [get_ports {da_bias_x[4]}]
set_property PACKAGE_PIN K21 [get_ports {da_bias_x[5]}]
set_property PACKAGE_PIN J22 [get_ports {da_bias_x[6]}]
set_property PACKAGE_PIN H22 [get_ports {da_bias_x[7]}]
set_property PACKAGE_PIN G22 [get_ports {da_bias_x[8]}]
set_property PACKAGE_PIN G21 [get_ports {da_bias_x[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_x[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk2]
set_property PACKAGE_PIN E19 [get_ports da_clk2]

set_property PACKAGE_PIN M18 [get_ports {da_bias_z[9]}]
set_property PACKAGE_PIN L18 [get_ports {da_bias_z[8]}]
set_property PACKAGE_PIN H20 [get_ports {da_bias_z[7]}]
set_property PACKAGE_PIN G20 [get_ports {da_bias_z[6]}]
set_property PACKAGE_PIN J20 [get_ports {da_bias_z[5]}]
set_property PACKAGE_PIN J21 [get_ports {da_bias_z[4]}]
set_property PACKAGE_PIN N20 [get_ports {da_bias_z[3]}]
set_property PACKAGE_PIN M20 [get_ports {da_bias_z[2]}]
set_property PACKAGE_PIN N18 [get_ports {da_bias_z[1]}]
set_property PACKAGE_PIN N19 [get_ports {da_bias_z[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_bias_z[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk3]
set_property PACKAGE_PIN F21 [get_ports da_clk3]


#例化
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]